Use stable branches that contain tag

diff --git a/.github/workflows/enable-bincompat-checking.yml b/.github/workflows/enable-bincompat-checking.yml
--- a/.github/workflows/enable-bincompat-checking.yml
+++ b/.github/workflows/enable-bincompat-checking.yml
@@ -37,20 +37,29 @@ jobs:
       branches: ${{ steps.determine-branches.outputs.branches }}
 
     steps:
-      - id: check-valid
+      - name: Check Valid
         run: |
           VERSION=${{ needs.determine_version.outputs.version }}
-          if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "valid=true" >> "$GITHUB_OUTPUT"
+          if [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
+            echo "Valid version!"
           else
-            echo "valid=false" >> "$GITHUB_OUTPUT"
+            echo "$VERSION is invalid!" >> $GITHUB_STEP_SUMMARY
+            exit 1
           fi
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
       - id: determine-branches
-        if: steps.check-valid.outputs.valid == 'true'
         run: |
           VERSION=${{ needs.determine_version.outputs.version }}
-          IFS=. read major minor micro <<<"${VERSION##*-}"
-          echo "branches=[\"$major.x\", \"$major.$minor.x\"]" >> "$GITHUB_OUTPUT"
+          touch branches.txt
+          STABLE=$(git for-each-ref --format='%(refname:short)' refs/remotes/origin/*.x)
+          for branch in $STABLE origin/main; do
+            if git merge-base --is-ancestor $VERSION $branch; then
+              echo ${branch#origin/} >> branches.txt
+            fi
+          done
+          echo "branches=$(jq -nR [inputs])" >> "$GITHUB_OUTPUT"
 
   open_prs:
     name: Open Pull Requests
@@ -62,8 +71,6 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
       - id: check-branch
         run: |
           if git show-branch origin/${{ matrix.branch }} ; then
@@ -74,7 +81,9 @@ jobs:
       - name: Create file
         if: steps.check-branch.outputs.valid == 'true'
         run: |
-          echo ${{ needs.determine_version.outputs.version }} >> file.txt
+          VERSION=${{ needs.determine_version.outputs.version }}
+          VERSION_NO_V=${VERSION#v}
+          echo $VERSION_NO_V >> file.txt
       - name: Open PR
         if: steps.check-branch.outputs.valid == 'true'
         uses: peter-evans/create-pull-request@v5
